[package]
name = "qualsdorf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
erfurt = { path = "../erfurt/" }
float-cmp = "0.9.0"
itertools = "0.10.5"
statrs = "0.16.0"
